spring.application.name=ChatAppAPI
server.port=8082

# --- DATABASE CONFIGURATION ---
spring.datasource.driver-class-name=org.postgresql.Driver

# CRITICAL FIX: Changed port from 5432 to 6543 (Transaction Mode)
# This bypasses the "Max Clients" error
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres

spring.datasource.username=postgres.xrtfetjuucliztikszby
spring.datasource.password=Abhinav@1205

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- CONNECTION POOL SETTINGS ---
# Lowered to 5 to prevent exhausting Supabase limits
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

# Aggressively close idle connections to free up space
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000